# Generated by Django 4.2.11 on 2024-04-03 01:25

from django.db import migrations

def polulate_role(apps, schemaeditor):
  entries = {
    'developer': 'the person on the team who writes the code',
    'product_owner': 'the person on the team who responsible for defining what gets built',
    'scrum_master': 'the person on the team who keeps the team on track',
  }
  Role = apps.get_model('accounts', 'Role')
  for key, value in entries.items():
    role = Role(name=key, description=value)
    role.save()

def populate_team(apps, schemaeditor):
  entries = {
    'alpha': 'the team A',
    'bravo': 'the team B',
    'charlie': 'the team C',
  }
  Team = apps.get_model('accounts', 'Team')
  for key, value in entries.items():
    team_obj = Team(name=key, description=value)
    team_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
      migrations.RunPython(polulate_role),
      migrations.RunPython(populate_team),
    ]
